import { Time } from "@angular/common";
import { RoomSelectorComponent } from "../dashboard/rooms/room-selector/room-selector.component";
import { Role } from "./Role/role";

export class Utilisateur {

    id: bigint;
    username: string;
    password: string;
    lastname: string;
    firstname: string;
    email: string;
    dateDeNaissance: Date;
    cin: bigint;
    address: string;
    cps: bigint;
    telephone: number;
    fileName: string;
    pseudo: string;
    dateRec: Date;
    typeContrat: string;
    dateContrat: Date;
    famille:string;
    salaire:number;
    primeDeRendement:number;
    heuresDeTravail:Date;
    venteParHeure:number;
    objectifParJour:number;
    objectifParMois:number;
    dateDebutConge:Date;
    dateFinConge:Date;
    typeConge:string;

    primeDev:number;
    primeGlobal:number;
    primeParClient:number;
    primeStock:number;
    postV:string;
    codUser:number;
    raison:string;
    rc:string;
    respon1:string;
    fonction1:string;
    faxs:string;
    adrSiege:string;
    ruel:string;
    numRuel:string;
    cpl:string;
    villel:string;
    regionl:string;
    tell:string;
    faxl:string;
    adrLiv:string;
    region:string;
    taxe:string;
    ccb1:string;
    bank1:string;
    agence1:string;
    garanties:string;
    codGrp:string;
    modReg:string;
    domBan:string;
    echeance:number;
    crMax:number;
    derMvt:Date;
    credit:number;
    preVen:number;
    cumulAch:number;
    chifAff1:number;
    chifAff2:number;
    chifAff3:number;
    tauxRem:number;
    tauxCom:number;
    reste:number;
    tauxRes:number;
    connected:number;
    valRes:number;
    patron:string;
    rang:number;
    impaye:number;
    chqImpaye:number;
    efPort:number;
    efBanque:number;
    efNrecu:number;
    avCom:number;
    caution:string;
    benefice:number;
    tauxBene:number;
    recFff:number;
    tva:number;
    cle:number;
    soldDep:number;
    interet:number;
    regChq:number;
    regEff:number;
    regEsp:number;
    facInst:number;
    avoir:number;
    effInst:number;
    soldeBq:number;
    creance:number;
    effEnc:number;
    effEsc:number;
    comission:number;
    bloc:string;
    codeTva:string;
    remOrg:number;
    avance:number;
    chqPf:number;
    retenue:number;
    regVir:number;
    avN1:number;
    classe:string;
    ristourne:number;
    caPrev:number;
    soldeCpf:number;
    soldeImp:number;
    soldeEpf:number;
    datFFac:Date;
    datGFac:string;
    caMens:number;
    crImax:number;
    fcreN1:number;
    fcreN2:number;
    freglN1:number;
    freglN2:number;
    fescN1:number;
    fescN2:number;
    fbkN1:number;
    fbkN2:number;
    fefpN1:number;
    fefpN2:number;
    fchpN1:number;
    fchpN2:number;
    fefnrN1:number;
    fefnrN2:number;
    icreN1:number;
    icreN2:number;
    ireglN1:number;
    ireglN2:number;
    iescN1:number;
    iescN2:number;
    ibkN1:number;
    ibkN2:number;
    iefpN1:number;
    iefpN2:number;
    ichpN1:number;
    ichpN2:number;
    iefnrN1:number;
    iefnrN2:number;
    datOuvr:string;
    command:string;
    remExp:number;
    chefMag:string;
    jourVisit:string;
    instance:boolean;
    comptant:boolean;
    bl:boolean;
    natLiv:string;
    mois1:number;
    mois2:number;
    mois3:number;
    mois4:number;
    mois5:number;
    mois6:number;
    mois7:number;
    mois8:number;
    mois9:number;
    mois10:number;
    mois11:number;
    mois12:number;
    datDerLi:string;
    margePour:number;
    margeVal:number;
    credblEnc:number;
    credinstec:number;
    observatio:string;
    observ:string;
    gouv1:string;
    gouv2:string;
    natcaution:string;
    cheque:boolean;
    espece:boolean;
    traite:boolean;
    crRef:number;
    soldTerm:number;
    chqImp:number;
    criRef:number;
    remFam:string;
    reglement:number;
    delai:number;
    nbTranche:number;
    codSteq:string;
    reference:number;
    sansRet:string;
    cliGroup:string;
    tauxMarge:number;
    showPassword:string;
    zone:string;
    roles:Role;
    role:string[];
    authorisation: string;
}